# Project: Project4
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Source.o
LINKOBJ  = Source.o
LIBS     = -L"C:/Users/Matthew/OneDrive/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -L"C:/SDL-devel-1.2.15-mingw32.tar/SDL-1.2.15/lib" -static-libgcc -mwindows -lmingw32 -lSDLmain -lSDL -m32
INCS     = -I"C:/Users/Matthew/OneDrive/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/Matthew/OneDrive/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Matthew/OneDrive/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Matthew/OneDrive/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/Matthew/OneDrive/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Matthew/OneDrive/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Matthew/OneDrive/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/SDL-devel-1.2.15-mingw32.tar/SDL-1.2.15/include"
BIN      = Project4.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Source.o: Source.cpp
	$(CPP) -c Source.cpp -o Source.o $(CXXFLAGS)
